spring.application.name=dealkartbd
spring.datasource.url=jdbc:postgresql://localhost:5432/dealkart_db
spring.datasource.username=dealkart_user
spring.datasource.password=dealkart1122
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.jwt.secret=mysecretkey123mysecretkey123mysecretkey123mysecretkey123mysecretkey123mysecretkey123mysecretkey123mysecretkey123
app.jwt.expiration=86400000
auth.login.path=/api/auth/login

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-app@gmail.com
spring.mail.password=your-app-gmail-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Base URL
app.base-url=http://localhost:8080
